version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: remove_app.sh
  ApplicationStart:
    - location: start_app.sh
      timeout: 60
      runas: ec2-user